import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { basename, join } from "node:path";
import type { Logger } from "./logger";

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

export const GENERATED_HEADER = "<!-- generated by fixbot -->";
export const CONTEXT_BUDGET_CHARS = 8000;
export const CONTEXT_FILENAME = "project-context.md";
export const FIXBOT_DIR = ".fixbot";

// ---------------------------------------------------------------------------
// truncateWithNote
// ---------------------------------------------------------------------------

export function truncateWithNote(content: string, budget: number): string {
	if (content.length <= budget) {
		return content;
	}
	const note = `\n<!-- truncated: exceeded ${budget} char budget -->`;
	return content.slice(0, budget) + note;
}

// ---------------------------------------------------------------------------
// parseCacheMetadata
// ---------------------------------------------------------------------------

export function parseCacheMetadata(
	content: string,
): { timestamp: string; commitHash: string } | undefined {
	if (!content.startsWith(GENERATED_HEADER)) {
		return undefined;
	}
	const timestampMatch = content.match(/<!-- timestamp: (.+?) -->/);
	const commitMatch = content.match(/<!-- commit: (.+?) -->/);
	if (!timestampMatch) {
		return undefined;
	}
	return {
		timestamp: timestampMatch[1],
		commitHash: commitMatch ? commitMatch[1] : undefined as unknown as string,
	};
}

// ---------------------------------------------------------------------------
// isCacheValid
// ---------------------------------------------------------------------------

export function isCacheValid(
	metadata: { timestamp: string; commitHash: string | undefined },
	currentCommit: string | undefined,
): boolean {
	if (!metadata.commitHash || !currentCommit) {
		return false;
	}
	return metadata.commitHash === currentCommit;
}

// ---------------------------------------------------------------------------
// buildCacheHeader
// ---------------------------------------------------------------------------

export function buildCacheHeader(commitHash: string): string {
	const lines = [
		GENERATED_HEADER,
		`<!-- timestamp: ${new Date().toISOString()} -->`,
		`<!-- commit: ${commitHash} -->`,
		"",
	];
	return lines.join("\n");
}

// ---------------------------------------------------------------------------
// discoverExistingDocs
// ---------------------------------------------------------------------------

export function discoverExistingDocs(workspaceDir: string): {
	claudeMd?: string;
	agentsMd?: string;
} {
	const result: { claudeMd?: string; agentsMd?: string } = {};

	// CLAUDE.md: prefer root over .claude/CLAUDE.md
	const rootClaudeMd = join(workspaceDir, "CLAUDE.md");
	const nestedClaudeMd = join(workspaceDir, ".claude", "CLAUDE.md");
	if (existsSync(rootClaudeMd)) {
		try {
			result.claudeMd = readFileSync(rootClaudeMd, "utf-8");
		} catch {}
	} else if (existsSync(nestedClaudeMd)) {
		try {
			result.claudeMd = readFileSync(nestedClaudeMd, "utf-8");
		} catch {}
	}

	// AGENTS.md
	const agentsMd = join(workspaceDir, "AGENTS.md");
	if (existsSync(agentsMd)) {
		try {
			result.agentsMd = readFileSync(agentsMd, "utf-8");
		} catch {}
	}

	return result;
}

// ---------------------------------------------------------------------------
// mergeExistingDocs
// ---------------------------------------------------------------------------

export function mergeExistingDocs(
	claudeMd: string | undefined,
	agentsMd: string | undefined,
): { content: string; source: string } | undefined {
	if (!claudeMd && !agentsMd) {
		return undefined;
	}
	if (claudeMd && agentsMd) {
		const content = [
			"## From CLAUDE.md",
			"",
			claudeMd,
			"",
			"## From AGENTS.md",
			"",
			agentsMd,
		].join("\n");
		return { content, source: "merged" };
	}
	if (claudeMd) {
		return { content: claudeMd, source: "claude-md" };
	}
	return { content: agentsMd!, source: "agents-md" };
}

// ---------------------------------------------------------------------------
// Framework detection
// ---------------------------------------------------------------------------

interface FrameworkDetection {
	name: string;
	package: string;
}

const KNOWN_FRAMEWORKS: FrameworkDetection[] = [
	{ name: "React", package: "react" },
	{ name: "Next.js", package: "next" },
	{ name: "Vue", package: "vue" },
	{ name: "Nuxt", package: "nuxt" },
	{ name: "Angular", package: "@angular/core" },
	{ name: "Svelte", package: "svelte" },
	{ name: "Express", package: "express" },
	{ name: "Fastify", package: "fastify" },
	{ name: "Hono", package: "hono" },
	{ name: "Nest.js", package: "@nestjs/core" },
	{ name: "TypeScript", package: "typescript" },
	{ name: "Tailwind CSS", package: "tailwindcss" },
	{ name: "Prisma", package: "prisma" },
	{ name: "Drizzle", package: "drizzle-orm" },
];

export function detectFrameworks(
	packageJson: Record<string, unknown>,
): FrameworkDetection[] {
	const deps = {
		...(typeof packageJson.dependencies === "object" && packageJson.dependencies !== null
			? (packageJson.dependencies as Record<string, string>)
			: {}),
		...(typeof packageJson.devDependencies === "object" && packageJson.devDependencies !== null
			? (packageJson.devDependencies as Record<string, string>)
			: {}),
	};

	return KNOWN_FRAMEWORKS.filter((fw) => fw.package in deps);
}

// ---------------------------------------------------------------------------
// detectLanguage
// ---------------------------------------------------------------------------

export function detectLanguage(
	workspaceDir: string,
	packageJson?: Record<string, unknown>,
): string {
	if (existsSync(join(workspaceDir, "Cargo.toml"))) return "Rust";
	if (existsSync(join(workspaceDir, "go.mod"))) return "Go";
	if (existsSync(join(workspaceDir, "pyproject.toml"))) return "Python";
	if (existsSync(join(workspaceDir, "setup.py"))) return "Python";
	if (existsSync(join(workspaceDir, "requirements.txt"))) return "Python";
	if (existsSync(join(workspaceDir, "Gemfile"))) return "Ruby";
	if (existsSync(join(workspaceDir, "build.gradle")) || existsSync(join(workspaceDir, "pom.xml"))) return "Java";

	if (packageJson) {
		const allDeps = {
			...(typeof packageJson.dependencies === "object" && packageJson.dependencies !== null
				? (packageJson.dependencies as Record<string, string>)
				: {}),
			...(typeof packageJson.devDependencies === "object" && packageJson.devDependencies !== null
				? (packageJson.devDependencies as Record<string, string>)
				: {}),
		};
		if ("typescript" in allDeps) return "TypeScript";
		return "JavaScript";
	}

	if (existsSync(join(workspaceDir, "package.json"))) {
		try {
			const pkg = JSON.parse(readFileSync(join(workspaceDir, "package.json"), "utf-8"));
			const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
			if ("typescript" in allDeps) return "TypeScript";
			return "JavaScript";
		} catch {}
	}

	return "Unknown";
}

// ---------------------------------------------------------------------------
// generateReadmeSection
// ---------------------------------------------------------------------------

export function generateReadmeSection(workspaceDir: string): string | undefined {
	const readmePath = join(workspaceDir, "README.md");
	if (!existsSync(readmePath)) {
		return undefined;
	}
	try {
		const content = readFileSync(readmePath, "utf-8");
		// Extract everything up to the second heading (##)
		const lines = content.split("\n");
		const sectionLines: string[] = [];
		let foundFirstHeading = false;
		for (const line of lines) {
			if (line.startsWith("## ")) {
				if (foundFirstHeading) break;
				// This shouldn't happen as first heading is typically #
			}
			if (line.startsWith("# ")) {
				foundFirstHeading = true;
			}
			sectionLines.push(line);
		}
		const section = sectionLines.join("\n").trim();
		return section || undefined;
	} catch {
		return undefined;
	}
}

// ---------------------------------------------------------------------------
// generateDirectoryListing
// ---------------------------------------------------------------------------

const ALLOWED_DOTDIRS = new Set([".github"]);

export function generateDirectoryListing(workspaceDir: string): string {
	try {
		const entries = readdirSync(workspaceDir, { withFileTypes: true });
		const lines: string[] = [];
		for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
			// Hide dotfiles/dotdirs except allowed ones
			if (entry.name.startsWith(".") && !ALLOWED_DOTDIRS.has(entry.name)) {
				continue;
			}
			if (entry.isDirectory()) {
				lines.push(`${entry.name}/`);
			} else {
				lines.push(entry.name);
			}
		}
		return lines.join("\n");
	} catch {
		return "";
	}
}

// ---------------------------------------------------------------------------
// tryGetHeadCommitSync
// ---------------------------------------------------------------------------

export function tryGetHeadCommitSync(workspaceDir: string): string | null {
	try {
		const gitDir = join(workspaceDir, ".git");
		if (!existsSync(gitDir)) return null;

		const headPath = join(gitDir, "HEAD");
		const headContent = readFileSync(headPath, "utf-8").trim();

		// Detached HEAD - raw commit hash
		if (!headContent.startsWith("ref: ")) {
			return headContent;
		}

		// Symbolic ref
		const ref = headContent.slice(5);
		const refPath = join(gitDir, ref);
		if (existsSync(refPath)) {
			return readFileSync(refPath, "utf-8").trim();
		}

		// Packed refs fallback
		const packedRefsPath = join(gitDir, "packed-refs");
		if (existsSync(packedRefsPath)) {
			const packedRefs = readFileSync(packedRefsPath, "utf-8");
			for (const line of packedRefs.split("\n")) {
				if (line.startsWith("#") || line.trim() === "") continue;
				const parts = line.split(" ");
				if (parts.length >= 2 && parts[1] === ref) {
					return parts[0];
				}
			}
		}

		return null;
	} catch {
		return null;
	}
}

// ---------------------------------------------------------------------------
// generateProjectContext
// ---------------------------------------------------------------------------

export function generateProjectContext(workspaceDir: string): string {
	const sections: string[] = [];
	const projectName = basename(workspaceDir);

	// Try to read package.json
	let packageJson: Record<string, unknown> | undefined;
	const pkgPath = join(workspaceDir, "package.json");
	if (existsSync(pkgPath)) {
		try {
			packageJson = JSON.parse(readFileSync(pkgPath, "utf-8"));
		} catch {}
	}

	const name = (packageJson && typeof packageJson.name === "string" ? packageJson.name : projectName) || projectName;
	const language = detectLanguage(workspaceDir, packageJson);
	const frameworks = packageJson ? detectFrameworks(packageJson) : [];

	// Header
	sections.push(`# ${name}`);
	sections.push("");

	// Language & frameworks
	if (language !== "Unknown" || frameworks.length > 0) {
		const parts: string[] = [];
		if (language !== "Unknown") parts.push(`**Language:** ${language}`);
		if (frameworks.length > 0) {
			parts.push(`**Frameworks:** ${frameworks.map((f) => f.name).join(", ")}`);
		}
		sections.push(parts.join("  \n"));
		sections.push("");
	}

	// Scripts
	if (packageJson && typeof packageJson.scripts === "object" && packageJson.scripts !== null) {
		const scripts = packageJson.scripts as Record<string, string>;
		const scriptNames = Object.keys(scripts);
		if (scriptNames.length > 0) {
			sections.push("## Scripts");
			sections.push("");
			for (const name of scriptNames.slice(0, 15)) {
				sections.push(`- \`${name}\`: \`${scripts[name]}\``);
			}
			sections.push("");
		}
	}

	// README excerpt
	const readmeSection = generateReadmeSection(workspaceDir);
	if (readmeSection) {
		sections.push("## README Excerpt");
		sections.push("");
		sections.push(readmeSection);
		sections.push("");
	}

	// Directory listing
	const dirListing = generateDirectoryListing(workspaceDir);
	if (dirListing) {
		sections.push("## Directory Structure");
		sections.push("");
		sections.push("```");
		sections.push(dirListing);
		sections.push("```");
		sections.push("");
	}

	return sections.join("\n").trim();
}

// ---------------------------------------------------------------------------
// getProjectContext (main entry point)
// ---------------------------------------------------------------------------

export function getProjectContext(
	workspaceDir: string,
	log?: Logger,
): { content: string; source: string } {
	try {
		const fixbotDir = join(workspaceDir, FIXBOT_DIR);
		const contextPath = join(fixbotDir, CONTEXT_FILENAME);

		// 1. User-provided file (non-generated)
		if (existsSync(contextPath)) {
			try {
				const content = readFileSync(contextPath, "utf-8");
				const metadata = parseCacheMetadata(content);
				if (!metadata) {
					// User-provided (not auto-generated)
					log?.debug?.("using user-provided project context");
					return { content, source: "user-provided" };
				}

				// Check cache validity
				const currentCommit = tryGetHeadCommitSync(workspaceDir);
				if (isCacheValid(metadata, currentCommit ?? undefined)) {
					log?.debug?.("using cached generated project context");
					// Strip the generated header and metadata for the returned content
					const bodyStart = content.indexOf("\n\n");
					const body = bodyStart >= 0 ? content.slice(bodyStart + 2) : content;
					return { content: body, source: metadata.commitHash ? "generated" : "generated" };
				}
				log?.debug?.("cached project context is stale, regenerating");
			} catch {
				// Fall through to discovery
			}
		}

		// 2. Discover CLAUDE.md / AGENTS.md
		const docs = discoverExistingDocs(workspaceDir);
		const merged = mergeExistingDocs(docs.claudeMd, docs.agentsMd);
		if (merged) {
			log?.debug?.(`using ${merged.source} as project context`);
			const content = truncateWithNote(merged.content, CONTEXT_BUDGET_CHARS);
			// Cache result
			writeCache(workspaceDir, content, log);
			return { content, source: merged.source };
		}

		// 3. Generate from project structure
		const generated = generateProjectContext(workspaceDir);
		if (generated && generated.trim().length > 0) {
			const content = truncateWithNote(generated, CONTEXT_BUDGET_CHARS);
			writeCache(workspaceDir, content, log);
			return { content, source: "generated" };
		}

		return { content: "", source: "none" };
	} catch (error) {
		// Graceful degradation: never throw
		log?.warn?.(`project context discovery failed: ${error instanceof Error ? error.message : String(error)}`);
		return { content: "", source: "none" };
	}
}

// ---------------------------------------------------------------------------
// writeCache (internal)
// ---------------------------------------------------------------------------

function writeCache(workspaceDir: string, content: string, log?: Logger): void {
	try {
		const fixbotDir = join(workspaceDir, FIXBOT_DIR);
		mkdirSync(fixbotDir, { recursive: true });
		const commitHash = tryGetHeadCommitSync(workspaceDir);
		const header = buildCacheHeader(commitHash ?? "unknown");
		const contextPath = join(fixbotDir, CONTEXT_FILENAME);
		writeFileSync(contextPath, header + content, "utf-8");
	} catch (error) {
		log?.warn?.(`failed to write project context cache: ${error instanceof Error ? error.message : String(error)}`);
	}
}

// ---------------------------------------------------------------------------
// _testing export for test access to internals
// ---------------------------------------------------------------------------

export const _testing = {
	GENERATED_HEADER,
	CONTEXT_BUDGET_CHARS,
	CONTEXT_FILENAME,
	FIXBOT_DIR,
	truncateWithNote,
	parseCacheMetadata,
	isCacheValid,
	buildCacheHeader,
	discoverExistingDocs,
	mergeExistingDocs,
	detectFrameworks,
	detectLanguage,
	generateReadmeSection,
	generateDirectoryListing,
	generateProjectContext,
	tryGetHeadCommitSync,
};
